# name 标识一下这个 ci 文件名称，纯语义化的项，没有配置意义
name: Replace Test

# on 配置项用于配置该仓库的什么分支触发什么事件后进行该 ci 的调用
on:
  pull_request_target:
    branches: [ "main" ]
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs是一个功能脚本的维度集合。比如配置检测库语法，发布库，可以作为两个工作(job)。一个yml文件可以运行多个job。
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    # 该操作跑在什么环境之下，支持 Ubuntu/Windows/macOS。
    runs-on: ubuntu-latest
    # step 标识一系列按续执行的最小工作单元
    steps:
      # 运行单个的 shell
      - name: Run a one-line script
        run: echo Replace taking!
        
      - name: Replace test
        run: |
          git clone https://github.com/wangxingran222/jiamingge1111.git
          cd jiamingge1111
          cwd
          python tests/replace.py
          git config --global user.email "13982596716@163.com"
          git config --global user.name "Test"
          git add .
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
